### PR TITLE
Fix issue #154 Enhanced URL Filtering for Resources

### PR DESCRIPTION
**Pull request by D-01576**
Close issue #154 

## What Functionality Are You Suggesting?
Functionality: This update enhances the URL handling by appending the selected category, price, and search terms as query parameters. Users can now filter resources based on multiple criteria, which will be reflected in the URL for easy sharing and bookmarking. Previously, this only handled the URL for the category, but after my update, it now supports all three filters.

## Why Will This Benefit The Community?
Benefit: By allowing the URL to include all filter options, users can easily return to specific filtered results or share their searches with others. This improvement enhances usability and ensures a more consistent experience when navigating the resource library.

### CODE REVIEW

**Comment by Siraj01576** [comment]
@LamboCreeper please review this PR

**Comment by LamboCreeper** [comment]
@Siraj01576 please can you fix lint and build, thanks

**Comment by Siraj01576** [comment]
> er

Ok

**Comment by LamboCreeper** [comment]
Closing due to inactivity

**Pull request closed without merging**
