### PR TITLE
Fix issue #148: Improved by automatic switching between dark and ligh…

### PR DESCRIPTION
**Pull request by Siraj01576**
#### What this PR does:
- automatic switching between dark and light mode based on the user's system preference

### CODE REVIEW

**Comment by Siraj01576** [comment]
@LamboCreeper, @Jason2605 please review this PR

**Review by LamboCreeper — COMMENTED** [review]
Thanks for this! Looks good, but could you update it so there is no black text on the blue buttons and hero banners. It is hard to read (see below):
image
image

**Comment by Siraj01576** [comment]
@LamboCreeper, Ok

**Review by LamboCreeper — APPROVED** [review]
Great! Thank you for this

**Pull request merged**
